import { Comfortaa } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata = {
  title: "Marea Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} dark:bg-dark-blue dark:text-arena`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
